@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "AbsolutSinema Storage" #F4F6F6{
Class "<<interface>>\nAbsolutSinemaStorage" as AbsolutSinemaStorage
Class JsonAbsolutSinemaStorage
Class JsonSerializableAbsolutSinema
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" AbsolutSinemaStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> AbsolutSinemaStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAbsolutSinemaStorage .up.|> AbsolutSinemaStorage
JsonAbsolutSinemaStorage ..> JsonSerializableAbsolutSinema
JsonSerializableAbsolutSinema --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
