@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedAbsolutSinema" as VersionedAbsolutSinema MODEL_COLOR
end box

[-> Model : undoAbsolutSinema()
activate Model

Model -> VersionedAbsolutSinema : undo()
activate VersionedAbsolutSinema

VersionedAbsolutSinema -> VersionedAbsolutSinema :resetData(ReadOnlyAbsolutSinema)
VersionedAbsolutSinema --> Model :
deactivate VersionedAbsolutSinema

[<-- Model
deactivate Model

@enduml
